### PR TITLE
Social Graph (fork)

### LINKED ISSUE #23: Social Graph and Reputation
Now that we have a basic social graph #22 , we can start digging into several interesting ideas for handling reputation: web-of-distrust and NIP-32.

## Web-of-Distrust

- basic social graph, but balance follows (good) with mutes and reports (bad)
- prevent popularity contests by taking things into account besides just follows
- echo chambers may be identified if there is a lack of dissonance
- follows, mutes, and reports are considered, and weighted based on vector (2nd degree's opinion of 1st degree is lighter; 1st degree's opinion of 2nd degree is heavier)
- should allow for one to change their mind about someone and have that reflected in the updated graph

## NIP-32 https://github.com/nostr-protocol/nips/pull/46

- assign a reputation event to anyone for anything
- can augment a basic social graph
- not sure about the interplay between reputation ratings and follow/mute/report.

### PR DESCRIPTION
**Pull request by arkin0x**
added distance and weight function
fixed tests, added tests for distance
cleanup

### CODE REVIEW

**Comment by arkin0x** [comment]
Still left to do:

- [ ] write tests for ArcadeSocial.weight()
- [ ] figure out how to leverage ArcLib.ArcadeDB so we're not building the social graph only in memory but are persisting it somehow
- [ ] implement reputation function in ArcadeSocial where you pass an evaluee's pubkey and label, and it gets all NIP-32 events for that label and applies the social graph weights to return a score for the pubkey.
- [ ] write tests for reputation

Bonus:

- [ ] figure out how to port graph creation and scores to nostr-tools

**Comment by arkin0x** [comment]
Social graph construction is now hitting the DB. Next I'll write tests for the reputation. I have to create some test reputation scores to do this, which will require me to make a little app to publish those.

@earonesty just fyi

**Comment by arkin0x** [comment]
@earonesty I don't know why CI is failing but it looks like the social graph tests passed: https://github.com/ArcadeLabsInc/arclib/actions/runs/5490780794/jobs/10006629008?pr=36#step:6:132

**Comment by arkin0x** [comment]
@earonesty please see the latest. Tests pass for retrieving a reputation score for a given pubkey ✅

**Comment by arkin0x** [comment]
The CI checks are not failing on the social graph code, which is the only code I've modified on this branch. Social tests passing here: https://github.com/ArcadeLabsInc/arclib/actions/runs/5495459692/jobs/10014872021?pr=36#step:6:78

**Comment by earonesty** [comment]
looks like you just need to pull in the latest branch.   you have
references to watermelon db, which we haven't been using for a while now

**Comment by arkin0x** [comment]
I merged main and had the darndest time getting my tests to pass. That was last week when I was sick. I tried running them today and, like magic, they all just work. I must have needed a reboot or something to get jest to behave, facepalm 

image

Had to screenshot it because I didn't believe it myself

**Pull request merged**
